### PR TITLE
Port to 1.19.2

### PR DESCRIPTION
**Pull request by CCr4ft3r**
Hi there :)

this mod is too good to let it go. I updated it to 1.19.2.
My branch includes a state that is ready to use and is already tested.

However I still created a draft pull request so that you can create a new branch "1.19.2" based on the 1.18.x branch. I will then change the target of this pull request to your 1.19.2 branch.

Please accept my pull request and publish the new version on CurseForge.
This would be great.

Sincerely CCr4ft3r

### CODE REVIEW

**Comment by itzme1on** [comment]
the creator of the mod does not respond to me, so I made another repository and will try to maintain the mod. you can make a pull request there https://github.com/itzme1on/AlcoCraft-Plus

**Comment by CCr4ft3r** [comment]
Thx for this info. Your repo doesn't seem to be public.
Do you already ported it to 1.19.2?

However I already tried to reach them on CurseForge and I will wait for some days to get an answer. 
If I get no answer I will probably publish it on CurseForge. I'm thinking of a multi-member page.

**Comment by itzme1on** [comment]
> Thx for this info. Your repo doesn't seem to be public. 

Oops... wait a minute

**Comment by itzme1on** [comment]
> Thx for this info. Your repo doesn't seem to be public. Do you already ported it to 1.19.2?
> 
> However I already tried to reach them on CurseForge and I will wait for some days to get an answer. If I get no answer I will probably publish it on CurseForge. I'm thinking of a multi-member page.

you can check my repo now
https://github.com/itzme1on/AlcoCraft-Plus

**Comment by CCr4ft3r** [comment]
Sorry for the late answer, but I hoped to receive an answer from the owner. 
I'm willing to push it to your repo and let you publish it on CurseForge under the following conditions:

- Giving credit to the original owner
- Using the same license
- Giving credit to me for porting it to 1.19.2

If you agree with these requests I will change the branch to yours. When could you publish it on CurseForge?

**Comment by itzme1on** [comment]
> Sorry for the late answer, but I hoped to receive an answer from the owner. I'm willing to push it to your repo and let you publish it on CurseForge under the following conditions:
> 
> * Giving credit to the original owner
> * Using the same license
> * Giving credit to me for porting it to 1.19.2
> 
> If you agree with these requests I will change the branch to yours? When could you publish it on CurseForge?

Yes, I have indicated Hadrus in the credits, and, of course, I will also indicate you as author

**Comment by CCr4ft3r** [comment]
Awesome👍

**Comment by CCr4ft3r** [comment]
Please create a 1.19.2-forge branch in your repo, to which I can change my target to.

**Comment by itzme1on** [comment]
> Please create a 1.19.2-forge branch, in which I can change my target to.

1 min

**Comment by itzme1on** [comment]
done

**Comment by CCr4ft3r** [comment]
Thx. But I just noticed that your repo isn't a fork of Hadrus repo so GitHub cannot find your branch/repo when creating a new pull request. So the only possible way is that you checkout my 1.19.2 branch, change the remote and push it to your repo.

Thanks in advance for maintaing this mod. I'm looking forward to the release. 
When are you planning to publish it on CurseForge?

**Comment by itzme1on** [comment]
> Thx. But I just noticed that your repo isn't a fork of Hadrus repo so GitHub cannot find your branch/repo when creating a new pull request. So the only possible way is that you checkout my 1.19.2 branch, change the remote and push it to your repo.
> 
> Thanks in advance for maintaing this mod. I'm looking forward to the release. When are you planning to publish it on CurseForge?

already published
https://www.curseforge.com/minecraft/mc-mods/alcocraft

**Comment by itzme1on** [comment]
> Thx. But I just noticed that your repo isn't a fork of Hadrus repo so GitHub cannot find your branch/repo when creating a new pull request. So the only possible way is that you checkout my 1.19.2 branch, change the remote and push it to your repo.
> 
> Thanks in advance for maintaing this mod. I'm looking forward to the release. When are you planning to publish it on CurseForge?

okay, let me finish my work and i copy your code to my repo
check your mail, i will invite you as collaborator

**Comment by CCr4ft3r** [comment]
Thx but I will probably not have time to contribute features/bugfixes in the future

**Pull request closed without merging**
